# Generated by Django 5.0.1 on 2024-01-26 18:23

import creditcards.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdesc', models.TextField(blank=True, null=True)),
                ('cimage', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('cparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_finshied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_address', models.CharField(max_length=150)),
                ('shipment_phone', models.CharField(max_length=50)),
                ('card_number', creditcards.models.CardNumberField(max_length=25)),
                ('expire', creditcards.models.CardExpiryField()),
                ('security_code', creditcards.models.SecurityCodeField(max_length=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=50, null=True)),
                ('pdesc', models.TextField(blank=True, null=True)),
                ('pprice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pcost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pdiscount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pactive', models.BooleanField(blank=True, default=True, null=True)),
                ('pcreated', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d')),
                ('pslug', models.SlugField(blank=True, null=True)),
                ('pnew', models.BooleanField(default=True)),
                ('pbestseller', models.BooleanField(default=False)),
                ('pcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='products.cat')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails_order', to='products.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails_product', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orderdetails',
            field=models.ManyToManyField(through='products.Orderdetails', to='products.product'),
        ),
        migrations.CreateModel(
            name='Myfavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='us', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.product')),
            ],
        ),
    ]
