# Generated by Django 5.0.1 on 2024-01-27 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_pdiscount_alter_product_pname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField()),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='products.product')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
